In [1]:
import tensorflow as tf

In [6]:
hello = tf.constant('Hello Ternsorflow!')
print(hello)

tf.Tensor(b'Hello Ternsorflow!', shape=(), dtype=string)


In [10]:
print("Tensorflow version: ",tf.__version__)

Tensorflow version:  2.16.1


In [11]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import datasets

In [12]:
mnist = tf.keras.datasets.mnist

In [13]:
# dividing them in training examples 
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 27s 2us/step


In [14]:
from tensorflow.keras import models

In [15]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape =(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

c:\Users\Ahmed\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [16]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.551247  , -0.27764532,  0.48049247, -0.17542322,  0.617371  ,
        -0.21421282,  0.22859648,  0.06331377, -0.1127765 , -0.3317829 ]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.15033878, 0.06562778, 0.14006923, 0.07269125, 0.16061583,
        0.06992557, 0.10887941, 0.09229206, 0.0773908 , 0.06216931]],
      dtype=float32)>

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.6603236

In [23]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8578 - loss: 0.4855
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9546 - loss: 0.1517
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9670 - loss: 0.1075
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9719 - loss: 0.0889
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9771 - loss: 0.0732


In [25]:
model.evaluate(x_test, y_test,verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9779 - loss: 0.0708


[0.0707649514079094, 0.9779000282287598]

In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [27]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.48318594e-07, 8.01974664e-09, 1.86092893e-06, 3.48874106e-04,
        2.56539123e-10, 2.02840488e-06, 1.79768581e-12, 9.99639869e-01,
        2.16884402e-07, 6.80768289e-06],
       [5.48427037e-09, 5.62023997e-05, 9.99930739e-01, 1.29630916e-05,
        1.07328742e-18, 4.20757686e-08, 2.28950331e-10, 5.13111472e-13,
        3.74611737e-08, 3.57420663e-13],
       [1.32452740e-07, 9.99307871e-01, 1.14168724e-04, 1.47797946e-05,
        1.24108683e-05, 3.34422543e-06, 2.79469950e-05, 1.93068146e-04,
        3.16112651e-04, 1.01755249e-05],
       [9.99987245e-01, 4.58952023e-08, 9.67688993e-06, 3.06316323e-08,
        2.94521556e-07, 1.21464893e-07, 1.64074743e-06, 1.98165452e-07,
        1.99497681e-08, 8.22547236e-07],
       [2.43976251e-06, 2.91336932e-09, 1.19504193e-06, 2.59900137e-08,
        9.96245563e-01, 3.89503521e-06, 5.05567232e-06, 1.99570877e-05,
        2.47590833e-06, 3.71934939e-03]], dtype=float32)>